### ISSUE TITLE
SmsClientBuilder的window参数无效

### ISSUE THREAD

**Issue by Foreverux** [Lihuanghe/sms-client#3]
<img width="971" alt="image" src="https://github.com/Lihuanghe/sms-client/assets/48756817/a6f499a9-0eaf-4848-9630-976f8329780c">

SmsClientBuilder中没有将window参数传递给EndpointEntity，导致无论设置多少，EndpointEntity的window都是默认值

**Comment by ponycloud235** [comment]
还真的是，感谢提醒，已调整。

还有个问题，如何限制每个窗口的并发数？

**Comment by ponycloud235** [comment]
看到了，在流量整形里面做设置
